"""Add versionable descriptions

Revision ID: 7904ce17ae34
Revises: 7145d5e7a458
Create Date: 2021-03-21 15:03:14.202100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7904ce17ae34'
down_revision = '7145d5e7a458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register_description',
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['register.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['description_revision.id'], )
    )
    op.create_table('field_description',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['description_revision.id'], )
    )
    op.create_table('table_description',
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['description_revision.id'], )
    )
    op.create_table('table_field_description',
    sa.Column('table_field_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['description_revision.id'], ),
    sa.ForeignKeyConstraint(['table_field_id'], ['table_field.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_field_description')
    op.drop_table('table_description')
    op.drop_table('field_description')
    op.drop_table('register_description')
    op.drop_table('description_revision')
    # ### end Alembic commands ###
